apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api
    zone: prod
  name: backend-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api
    zone: prod
  type: ClusterIP
status:
  loadBalancer: {}
