apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
    zone: prod
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      zone: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
        zone: prod
    spec:
      containers:
      - image: sithukyaw666/api:zeta
        name: api
        resources: {}
status: {}
