apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongo-sts
  labels:
    app: mongo-sts
    zone: prod
spec: 
  replicas: 5
  selector: 
    matchLabels:
      app: mongo-sts
      zone: prod
  volumeClaimTemplates:
    - metadata:
        name: mongo-pvc
      spec: 
        accessModes: 
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 500Mi
  template:
    metadata:
      labels: 
        app: mongo-sts
        zone: prod
    spec: 
      containers:
        - name: mongo-container
          image: mongo:4.4.18
          volumeMounts:
            - name: mongo-pvc
              mountPath: /data/db
          ports: 
            - containerPort: 27017
