apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mongo-sts
  labels:
    app: mongo-sts
    zone: prod
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: mongo-sts
      zone: prod
  template:
    metadata:
      labels: 
        app: mongo-sts
        zone: prod
    spec: 
      containers:
        - name: mongo-container
          image: mongo:latest
          ports: 
            - containerPort: 27017
