apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-db
    spec:
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: mongo-pvc
      containers:
      - image: mongo:4.4.18
        name: mongo
        volumeMounts:
          - name: mongo-vol
            mountPath: "/data/db"
        resources: {}
status: {}
