apiVersion: v1
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html =404;
      }
      location /get/ {
        proxy_pass http://backend-service:8000;
      }
      location /put/ {
        proxy_pass http://backend-service:8000;
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-configmap
