apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    zone: prod
  name: ecommerce-website
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
    zone: prod
  type: LoadBalancer
status:
  loadBalancer: {}
